package main

import "reasonix/internal/cowork"

var desktopCoworkStore = cowork.NewStore()

// CreateCoworkProject initializes the minimal Northwing manifest inside an
// existing workspace. Reasonix remains the owner of sessions, Goals, tools,
// permissions, memory, checkpoints, and execution state.
func (a *App) CreateCoworkProject(workspaceRoot, name string) (cowork.Project, error) {
	return desktopCoworkStore.Create(workspaceRoot, name)
}

// ValidateCoworkProjectWritable checks that the manifest and its metadata
// directory can accept an atomic update before the frontend creates a native
// Work session.
func (a *App) ValidateCoworkProjectWritable(workspaceRoot string) error {
	return desktopCoworkStore.ValidateWritable(workspaceRoot)
}

// LoadCoworkProject returns the project links used by the Northwing desktop
// surface without loading or duplicating session content.
func (a *App) LoadCoworkProject(workspaceRoot string) (cowork.Project, error) {
	return desktopCoworkStore.Load(workspaceRoot)
}

// CoworkProjectState returns one current CoWork project. When syncArtifacts is
// true, files under deliverables/<work-id> are hash-scanned and registered in a
// single manifest update before the state is returned.
func (a *App) CoworkProjectState(workspaceRoot string, syncArtifacts bool) cowork.ProjectState {
	_, _ = a.NormalizeWorkBindings(workspaceRoot)
	return desktopCoworkStore.State(workspaceRoot, syncArtifacts)
}

// CoworkProjectSummaries reads all visible project manifests behind one Wails
// call. The result contains counts and latest references only; it never loads
// session transcripts, artifact bodies, or Reasonix execution state.
func (a *App) CoworkProjectSummaries(workspaceRoots []string) []cowork.ProjectSummary {
	for _, root := range workspaceRoots {
		_, _ = a.NormalizeWorkBindings(root)
	}
	return desktopCoworkStore.Summaries(workspaceRoots)
}

// NorthwingCatalog returns a cheap cross-project projection for the Northwing
// product shell. It loads manifests and final selections without scanning
// deliverable directories or decoding transcripts.
func (a *App) NorthwingCatalog(workspaceRoots []string) (cowork.Catalog, error) {
	for _, root := range workspaceRoots {
		_, _ = a.NormalizeWorkBindings(root)
	}
	return desktopCoworkStore.Catalog(workspaceRoots)
}

// UpsertCoworkWork links a Northwing Work to the existing Reasonix session and
// Goal. The Work ID may be generated by the desktop before launch so the output
// directory is known to both the user brief and artifact scanner.
func (a *App) UpsertCoworkWork(workspaceRoot string, work cowork.WorkRef) (cowork.Project, error) {
	return desktopCoworkStore.LinkWork(workspaceRoot, work)
}

// UpdateCoworkWorkProgress persists the native Work session stage and acceptance
// counters while Reasonix remains authoritative for execution and todo state.
func (a *App) UpdateCoworkWorkProgress(workspaceRoot, workID, stage string, completedCriteria, totalCriteria int) (cowork.Project, error) {
	return desktopCoworkStore.UpdateWorkProgress(workspaceRoot, workID, stage, completedCriteria, totalCriteria)
}

// UpdateCoworkWorkProjection persists the full Northwing Work projection derived
// from Reasonix runtime evidence. The projection includes stage, current Harness
// step, acceptance state, and unresolved findings without submitting work.
func (a *App) UpdateCoworkWorkProjection(workspaceRoot string, workID string, projection cowork.WorkProjectionUpdate) (cowork.Project, error) {
	return desktopCoworkStore.UpdateWorkProjection(workspaceRoot, workID, projection)
}

// LinkCoworkWork is the primitive compatibility surface used by the first
// Northwing slice. New desktop code should prefer UpsertCoworkWork.
func (a *App) LinkCoworkWork(
	workspaceRoot string,
	title string,
	sessionPath string,
	goalID string,
	profile string,
) (cowork.Project, error) {
	return desktopCoworkStore.LinkWork(workspaceRoot, cowork.WorkRef{
		Title:       title,
		SessionPath: sessionPath,
		GoalID:      goalID,
		Profile:     profile,
	})
}

// SyncCoworkArtifacts discovers changed deliverables for all linked Works. It
// never reads file bodies into the UI or model context; only hashes and metadata
// enter the Northwing manifest.
func (a *App) SyncCoworkArtifacts(workspaceRoot string) (cowork.Project, error) {
	return desktopCoworkStore.SyncArtifacts(workspaceRoot)
}

// SetCoworkArtifactFinal selects a registered artifact version as the final
// output for its Work without moving or copying the file.
func (a *App) SetCoworkArtifactFinal(workspaceRoot, artifactID string) (cowork.ProjectState, error) {
	return desktopCoworkStore.SetFinalArtifact(workspaceRoot, artifactID)
}

// RegisterCoworkArtifact records a versioned deliverable already created inside
// the workspace. It hashes the file in place and never copies its contents into
// Northwing metadata.
func (a *App) RegisterCoworkArtifact(
	workspaceRoot string,
	path string,
	kind string,
	workID string,
) (cowork.Project, error) {
	return desktopCoworkStore.RegisterArtifact(workspaceRoot, cowork.Artifact{
		Path:   path,
		Kind:   kind,
		WorkID: workID,
	})
}
