package main

import "reasonix/internal/cowork"

var desktopCoworkStore = cowork.NewStore()

// CreateCoworkProject initializes the minimal Northwing manifest inside an
// existing workspace. Reasonix remains the owner of sessions, Goals, tools,
// permissions, memory, checkpoints, and execution state.
func (a *App) CreateCoworkProject(workspaceRoot, name string) (cowork.Project, error) {
	return desktopCoworkStore.Create(workspaceRoot, name)
}

// LoadCoworkProject returns the project links used by the Northwing desktop
// surface without loading or duplicating session content.
func (a *App) LoadCoworkProject(workspaceRoot string) (cowork.Project, error) {
	return desktopCoworkStore.Load(workspaceRoot)
}

// CoworkProjectState returns one current CoWork project. When syncArtifacts is
// true, files under deliverables/<work-id> are hash-scanned and registered in a
// single manifest update before the state is returned.
func (a *App) CoworkProjectState(workspaceRoot string, syncArtifacts bool) cowork.ProjectState {
	return desktopCoworkStore.State(workspaceRoot, syncArtifacts)
}

// CoworkProjectSummaries reads all visible project manifests behind one Wails
// call. The result contains counts and latest references only; it never loads
// session transcripts, artifact bodies, or Reasonix execution state.
func (a *App) CoworkProjectSummaries(workspaceRoots []string) []cowork.ProjectSummary {
	return desktopCoworkStore.Summaries(workspaceRoots)
}

// UpsertCoworkWork links a Northwing Work to the existing Reasonix session and
// Goal. The Work ID may be generated by the desktop before launch so the output
// directory is known to both the user brief and artifact scanner.
func (a *App) UpsertCoworkWork(workspaceRoot string, work cowork.WorkRef) (cowork.Project, error) {
	return desktopCoworkStore.LinkWork(workspaceRoot, work)
}

// LinkCoworkWork is the primitive compatibility surface used by the first
// Northwing slice. New desktop code should prefer UpsertCoworkWork.
func (a *App) LinkCoworkWork(
	workspaceRoot string,
	title string,
	sessionPath string,
	goalID string,
	profile string,
) (cowork.Project, error) {
	return desktopCoworkStore.LinkWork(workspaceRoot, cowork.WorkRef{
		Title:       title,
		SessionPath: sessionPath,
		GoalID:      goalID,
		Profile:     profile,
	})
}

// SyncCoworkArtifacts discovers changed deliverables for all linked Works. It
// never reads file bodies into the UI or model context; only hashes and metadata
// enter the Northwing manifest.
func (a *App) SyncCoworkArtifacts(workspaceRoot string) (cowork.Project, error) {
	return desktopCoworkStore.SyncArtifacts(workspaceRoot)
}

// SetCoworkArtifactFinal selects a registered artifact version as the final
// output for its Work without moving or copying the file.
func (a *App) SetCoworkArtifactFinal(workspaceRoot, artifactID string) (cowork.ProjectState, error) {
	return desktopCoworkStore.SetFinalArtifact(workspaceRoot, artifactID)
}

// RegisterCoworkArtifact records a versioned deliverable already created inside
// the workspace. It hashes the file in place and never copies its contents into
// Northwing metadata.
func (a *App) RegisterCoworkArtifact(
	workspaceRoot string,
	path string,
	kind string,
	workID string,
) (cowork.Project, error) {
	return desktopCoworkStore.RegisterArtifact(workspaceRoot, cowork.Artifact{
		Path:   path,
		Kind:   kind,
		WorkID: workID,
	})
}
